### ISSUE TITLE
Using "single" for the total value is unsafe

### ISSUE THREAD

**Issue by synopse** [gcarreno/1brc-ObjectPascal#20]
In the implementation, using a "single" type for adding a lot of values is known as not accurate.
With millions of values, adding new numbers may just be wrong because it exhausts the 32-bit precision of single.
This is why there are algorithms like https://en.wikipedia.org/wiki/Kahan_summation_algorithm

Implementation should better use Int64 values, and work as fixed resolution with temperature *10 64-bit integers.
And it will be faster.

BTW for a few thousand numbers, single is not faster than double, because the CPU L1 cache miss will probably be the bottleneck.

**Comment by gcarreno** [comment]
Hey @synopse,

First of all, thanks for hopping on board!! :people_hugging: 

Secondly: I think you're commenting on code that @paweld did.

If you feel that this is wrong and you have a better solution, please submit a PR.

Just make sure you don't break cross-IDE and cross-OS compatibility, because I think that @paweld made that decision after battling around with some cross-IDE issues.
But I'm not sure and would prefer that @paweld himself chimed in order for us to come to the bottom of this.

Cheers,
Gus

**Comment by synopse** [comment]
Note that I will make a PR but for my own version - I won't fix others.

"Single" seems used in all current versions, including baseline
https://github.com/gcarreno/1brc-ObjectPascal/blob/0a427c3726460b42169928f6ba4cae8a52191ac0/baseline/Common/baseline.common.pas#L22

But I will only make a version for FPC Linux x86_64. I will create another Issue about that.

**Comment by gcarreno** [comment]
Hey @synopse,

The code on the baseline came from Székely Balázs( aka GetMem ).
I just made sure it compiled and ran, did not do any more in-depth analysis.

The baseline is still a bit in flux since we still need a Delphi version of it and the common files to be cross all compatible.

If you think you can contribute to that, I welcome any PR you wanna present.

Cheers,
Gus

**Comment by paweld** [comment]
Hi Arnaud,
Thank you for your issue. We will look into it, but indeed with this amount of data, the single type may not be sufficient for temperature totals.
However, as for the `baseline` version performance, this is a deliberate procedure - the basic version is just to generate the correct (expected) result. It is up to the participants to show how to achieve this as quickly as possible.
Have a nice day.
Best regards,

**Comment by gcarreno** [comment]
Hey Arnaud(@synopse),

BTW, both the generator and the baseline are not entries.
They make part of the intent of making it fair for everyone. Or to create the necessary standards that everyone should abide to.

If you feel that the baseline needs a PR, then by all means please do it.

As @paweld mentioned, the baseline is just to produce an **official** output.
Being efficient has nothing to do with it. :smile: On the contrary, it should actually come dead last :rofl: 
But if that `single` will spoil the correct values, then yes, I do agree it needs changing.

Cheers,
Gus

**Comment by synopse** [comment]
The baseline is likely to produce consistent but wrong output, due to its use of "single" type as accumulator/total value.

When I will make my own mORMot2 code with Int64, we could check the results.

**Comment by gcarreno** [comment]
Hey Arnaux(@synopse),

> That is the point: even the baseline is likely to produce consistent but wrong output, due to its use of "single" type as accumulator/total value.

The baseline is still in flux.
And _sbalazs_ just sent me a `.patch` to clear that out.

Closing this one also.

Cheers,
Gus

**Comment by synopse** [comment]
> The baseline is still in flux.

= is a still a work in progress?

**Comment by gcarreno** [comment]
Hey Arnaud(@synopse),

> = is still a work in progress?

Correct, very, very WIP :smiley: 

Cheers,
Gus

**Comment by synopse** [comment]
I have finished a working version using mORMot 2 and a custom hash table (the custom hash table is 35% faster than the generic mORMot TDynArrayHashed in our case).

When compared with the current fastest:
```
ab@dev-ab:~/dev/github/1brc-ObjectPascal/bin$ time ./mormot data.csv 10 >resmot2.txt
real	0m5,328s
user	0m40,755s
sys	0m0,632s

ab@dev-ab:~/dev/github/1brc-ObjectPascal/bin$ time ./sbalazs data.csv 10 >ressb2.txt 
real	0m31,133s
user	3m31,080s
sys	0m18,672s
```

I don't publish it yet, because the output is not the same as with sblazs due to the rouding issue https://github.com/gcarreno/1brc-ObjectPascal/issues/22#issuecomment-2003202007
... and also because I prefer to see what others propose before putting my own proposal which has some unique performance tricks (which I did not see in even in the Java, C or Go versions).
