### ISSUE TITLE
Get rid of cross-OS and cross-IDE requirement

### ISSUE THREAD

**Issue by synopse** [gcarreno/1brc-ObjectPascal#21]
> You can only use pure Object Pascal with no calls to any operating system's API 

This requirement did not exist in the original Java challenge, and is pointless IMHO.

I would like to focus on FPC Linux x86_64.
Or at least be able to use mORMot 2 as cross-platform and cross-compiler layer.

**Comment by gcarreno** [comment]
Hey @synopse,

> This requirement did not exist in the original Java challenge, and is pointless IMHO.

Welp, in the Java world there is only Java.
In the Object Pascal world there is Free Pascal and Delphi.

In the spirit of making it fair for Free Pascal, Delphi, Linux and Windows we need to be as broad as possible, wouldn't you agree?

> Or at least be able to use mORMot 2 as cross-platform and cross-compiler layer.

I'm not quite sure what made you think that the use of any outside package would not be allowed. Please help me on this so I can make changes on the `README` file to make this clear.
The requirement is that it's pure Object Pascal and cross everything.
I'm quite sure that `mORMot 2` checks all the boxes and you're fine to use it.

Cheers,
Gus

**Comment by synopse** [comment]
Fine.
I will try to make a mORMot 2 version first, then a dedicated stand-alone version targeting Linux x86-64 with FPC only.

Note that existing code in your repository (even baseline) is FPC only, because it uses TFPHashList.
And trying to make cross-compiler and cross-platforms is not an easy task, especially with Delphi for Linux, which is more limited than the Delphi Win64 compiler (e.g. no shortstring, lower performance, long-standing inlining bugs). For Linux x86_64, the FPC compiler is a much better tool.

**Comment by gcarreno** [comment]
Hey Arnaux(@synopse),

> I will try to make a mORMot 2 version first, then a dedicated stand-alone version targeting Linux x86-64 with FPC only.

That's awesome news!!
Welcome to the fray!!

> Note that existing code in your repository (even baseline) is FPC only, because it uses TFPHashList.

You are correct, the Delphi counterpart hasn't been done yet, hence me saying that it's still a bit in flux.

And entries can be either done in Delphi or Free Pascal.
I'm gonna use my RAD Studio Enterprise 12.1 install on a VM, via `PAServer` to get all the Delphi( including CE ) ones compiled to the Linux host. And maybe use the new `LLVM` stuff if I can understand how to get there.

And I'll mark this one done.

Cheers,
Gus
