### ISSUE TITLE
Clarify average rounding

### ISSUE THREAD

**Issue by synopse** [gcarreno/1brc-ObjectPascal#22]
> result values per station in the format <min>/<mean>/<max>, rounded to one fractional digit

ROUNDED = truncated, I guess?

**Comment by gcarreno** [comment]
Hey Arnaud(@synopse),

I think it's `ceiling`. But I could be wrong.
I always get confused by the many rounding options and their names.
I think it's rounding `12.05` to `12.1` and `10.04` to `10.0`. Whatever this is, I'm always quite confused.

Cheers,
Gus

**Comment by gcarreno** [comment]
Hey Arnaud(@synopse),

Someone just mentioned that on the Java one it was rounded to positive infinity.
So `17.01` and `17.05` would both rounded to `17.1`.

Again, not quite sure if this is ceiling, or truncate or any other name.

Cheers,
Gus

**Comment by synopse** [comment]
Maybe it is https://github.com/gunnarmorling/1brc/blob/3372b6b29072af7359c5137bd1893d98828029a2/src/main/go/AlexanderYastrebov/calc.go#L241

**Comment by gcarreno** [comment]
With the latest patch from _sbalazs_ we now have the same rounding to positive infinity that exists in the mentioned Java code.
Closing.

**Comment by synopse** [comment]
The rounding function included is weird at most.
It is an adaptation from the challenge in go AFAICT.

The whole rounding to decimal in the challenge Java code may have been broken from the beginning.
https://www.baeldung.com/java-round-decimal-number#mathround-method

But even if we want to follow this path, at least our rouding function should be consistent.

For instance, the following values seems to be returned by PascalRound() as 
AbadiÃ¢nia=-37.5/-3.6/30.5, Abadla=-72.8/-40.1/-7.5
from -3.55177512355848  and -40.0573854201262 raw averages.

Where IMHO they should be returned as 
AbadiÃ¢nia=-37.5/-3.5/30.5, Abadla=-72.8/-40.0/-7.5

My guess is that the culprit is the t - x = 0.5 comparison which is never true due to additional digits.

**Comment by gcarreno** [comment]
Hey Arnaud,

I've mentioned this before and I will mention this again: You're always welcome to drop a PR to make stuff better.

In my opinion, this should've never been an Issue, but it should've been a PR from the start.
We now have 5 collaborators, not including me, that have made the choice of going the PR path.
And for all of them I've been quite happy to just merge their PRs, not many questions asked, if any.

> BTW you should better not close an Issue as "completed" without feedback from the reporter.

Thank you very much for the tip. I'll keep this in mind for future situations.
Nonetheless, my apologies if this troubled you!!

Cheers,
Gus
