### ISSUE TITLE
ReadMe should have partial example of the accepted result

### ISSUE THREAD

**Issue by EagleAglow** [gcarreno/1brc-ObjectPascal#33]
There seems to be an accepted result, with a published SHA256 value.  It would be helpful to get sample values for the text that is provided to the hash routine.  For example, my last run (to a file) resulted in the wrong hash, with the beginning of the output like:

{‘Abasān al Kabīrah=-18.2/-59.6/22.8, ‘Adrā=62.2/30.7/93.6, ‘Afrīn=28.7/0.7/56.6, ‘Ajab Shīr=-29.6/-70.7/11.3, ‘Ajlūn=33.4/4.3/62.3, ‘Ajmān=22.7/-9.2/54.5, ‘Akko=38.8/-3.6/80.6, ‘Alavīcheh=-61.7/-79.6/-43.8, ‘Alem T’ēna=6.2/-19.6/31.7, ‘Ālī Shahr=46.6/16.1/77.1, ‘Alīābād-e Katūl=-56.9/-84.1/-29.8, ‘Amrān=-15.4/-45.6/14.7, ‘Āmūdā=-58.1/-85.2/-30.9, ‘Anadān=11.4/-20.2/43.0, ‘Anbarābād=-39.1/-66.3/-12.2, ‘Aqrah=-35.9/-64.2/-7.8, ‘Ayn al ‘Arab=-15.3/-39.8/9.1, ‘Aynkāwah=38.6/5.4/72.2, ‘Ibrī=-50.3/-75.7/-24.9, ‘Izbat al Burj=23.6/-17.5/64.5, ‘Unayzah=56.2/14.0/98.5, ‘Utaybah=72.2/53.9/90.4, ’Aïn Abessa=0.8/-27.4/29.2, ’Aïn Abid=17.9/-3.1/38.9, ’Aïn Arnat=-25.2/-66.0/15.9, ’Aïn Azel=70.1/45.0/95.0, ’Aïn el Hammam=-44.0/-81.4/-7.4, ’Aïn Leuh=-71.3/-91.4/-51.6, ’Aïn Roua=-31.2/-54.3/-8.3, ’Ali Ben Sliman=66.1/40.4/91.9, ’Ayn Bni Mathar=-55.9/-86.9/-25.2, ```

I suspect I have not correctly implemented rounding, but I may be missing a BOM at the beginning, or an EOL at the end.   If possible, provide an excerpt from the beginning of the correct result in the ReadMe file.  Thank You!

**Comment by gcarreno** [comment]
Hey @EagleAglow,

You're absolutely right, and example should be provided.

I've added the file `data/baseline.output.gz` as the temporary version of the output until we can confirm that the Delphi version of the baseline will produce the same output.

Cheers,
Gus
